/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SocialMediaApp } from "./SocialMediaApp";
export * as factories from "./factories";
export { SocialMediaApp__factory } from "./factories/SocialMediaApp__factory";
