/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Social } from "./Social";
export * as factories from "./factories";
export { Social__factory } from "./factories/Social__factory";
